# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run the gemspec command
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{ryba}
  s.version = "0.1.1"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["oleg dashevskii"]
  s.date = %q{2010-07-26}
  s.description = %q{Russian names and addresses generator}
  s.email = %q{olegdashevskii@gmail.com}
  s.extra_rdoc_files = [
    "README.textile"
  ]
  s.files = [
    ".gitignore",
     "MIT-LICENSE",
     "README.textile",
     "Rakefile",
     "VERSION.yml",
     "lib/ryba.rb",
     "lib/ryba/address.rb",
     "lib/ryba/company.rb",
     "lib/ryba/data.rb",
     "lib/ryba/name.rb",
     "lib/ryba/phone_number.rb",
     "ryba.gemspec",
     "spec/ryba_spec.rb",
     "spec/spec_helper.rb"
  ]
  s.homepage = %q{http://github.com/be9/ryba}
  s.rdoc_options = ["--charset=UTF-8"]
  s.require_paths = ["lib"]
  s.rubygems_version = %q{1.3.7}
  s.summary = %q{Russian faker}
  s.test_files = [
    "spec/ryba_spec.rb",
     "spec/spec_helper.rb"
  ]

  if s.respond_to? :specification_version then
    current_version = Gem::Specification::CURRENT_SPECIFICATION_VERSION
    s.specification_version = 3

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
    else
    end
  else
  end
end

